### ISSUE TITLE
when I run train_bladder.py,I got a problem,could you give me some help?

### ISSUE THREAD

**Issue by pangda72** [LynnHg/Pytorch-medical-image-segmentation#4]
Hi,  @LynnHg 
Thank you for your [code.](https://blog.csdn.net/baidu_36511315/article/details/120902937?spm=1001.2014.3001.5501)  But when I run train_bladder.py,I got a problem:
#=================================================================================
E:\Anaconda3\envs\pytorch1.9\python.exe C:/Users/lenovo/Desktop/pytorch-medical-image-segmentation-master/train/train_bladder.py
C:/Users/lenovo/Desktop/pytorch-medical-image-segmentation-master/train/train_bladder.py:108: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  train_class_dices = np.array([0] * (bladder.num_classes - 1), dtype=np.float)
C:/Users/lenovo/Desktop/pytorch-medical-image-segmentation-master/train/train_bladder.py:109: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  val_class_dices = np.array([0] * (bladder.num_classes - 1), dtype=np.float)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lenovo\Desktop\pytorch-medical-image-segmentation-master\train\train_bladder.py", line 3, in <module>
    import torch
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 114, in _main
        exitcode = _main(fd)prepare(preparation_data)

  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 114, in _main
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 225, in prepare
    prepare(preparation_data)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 263, in run_path
    run_name="__mp_main__")
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 85, in _run_code
    pkg_name=pkg_name, script_name=fname)    
exec(code, run_globals)  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 96, in _run_module_code

  File "C:\Users\lenovo\Desktop\pytorch-medical-image-segmentation-master\train\train_bladder.py", line 3, in <module>
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 85, in _run_code
    import torch
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\__init__.py", line 124, in <module>
    exec(code, run_globals)
  File "C:\Users\lenovo\Desktop\pytorch-medical-image-segmentation-master\train\train_bladder.py", line 3, in <module>
        import torch
raise err
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\__init__.py", line 124, in <module>
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\lib\cudnn_adv_infer64_8.dll" or one of its dependencies.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lenovo\Desktop\pytorch-medical-image-segmentation-master\train\train_bladder.py", line 3, in <module>
    import torch
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\Anaconda3\envs\pytorch1.9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lenovo\Desktop\pytorch-medical-image-segmentation-master\train\train_bladder.py", line 3, in <module>
    import torch
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\nn\functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
epoch: 1 - iters: 1 - loss: 0.943 - mean: 0.05698 - bladder: 0.07835- tumor: 0.0356  - time: 2.1e+01
Traceback (most recent call last):
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\utils\data\dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "E:\Anaconda3\envs\pytorch1.9\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/pytorch-medical-image-segmentation-master/train/train_bladder.py", line 197, in <module>
    main()
  File "C:/Users/lenovo/Desktop/pytorch-medical-image-segmentation-master/train/train_bladder.py", line 101, in main
    train(train_loader, val_loader, net, criterion, optimizer, scheduler, None, early_stopping, n_epoch, 0)
  File "C:/Users/lenovo/Desktop/pytorch-medical-image-segmentation-master/train/train_bladder.py", line 116, in train
    for batch, ((input, mask), file_name) in enumerate(train_loader, 1):
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\utils\data\dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\utils\data\dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "E:\Anaconda3\envs\pytorch1.9\lib\site-packages\torch\utils\data\dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 64716, 62700, 66100, 65204, 64664) exited unexpectedly

Process finished with exit code 1
#=================================================================================

I don't know what the problem is.Could you give me some help?
Ps:my pytoch version is 1.2 and 1.9. 
Looking forward yout reply.
Thanks in advance.
Best.

**Comment by pangda72** [comment]
Hi @LynnHg 

I have solved this problem.It's because of my computer. I have successfully run it on another device. Thank you for sharing such a good repo, it will be a great help to me.Thank you very much again.

Hope you have a good day!
Best wishes.
